//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface CreateCollectionRequest {
    name?: string | undefined;
    description?: string | undefined;
    embeddingSize?: number | undefined;
}

export interface CreateCollectionResponse {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    cratedAt?: Date;
    embeddingSize?: number | undefined;
}

export interface CreateVectorRequest {
    class?: string | undefined;
    description?: string | undefined;
    collectionId?: string;
    embedding?: number[] | undefined;
}

export interface CreateVectorResponse {
    id?: string;
    class?: string | undefined;
    description?: string | undefined;
    collectionId?: string;
    embedding?: number[] | undefined;
}

export interface GetCollectionResponse {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
    createdAt?: Date;
    lastUpdated?: Date | undefined;
    embeddingSize?: number | undefined;
}

export interface GetCollectionResponsePaginated {
    page?: number;
    pageSize?: number;
    totalCount?: number | undefined;
    totalPages?: number | undefined;
    items?: GetCollectionResponse[] | undefined;
}

export interface GetVectorResponse {
    id?: string;
    class?: string | undefined;
    description?: string | undefined;
    collectionId?: string;
    embedding?: number[] | undefined;
    createdAt?: Date;
    lastUpdated?: Date | undefined;
}

export interface GetVectorResponsePaginated {
    page?: number;
    pageSize?: number;
    totalCount?: number | undefined;
    totalPages?: number | undefined;
    items?: GetVectorResponse[] | undefined;
}

export interface UpdateCollectionRequest {
    id?: string;
    name?: string | undefined;
    description?: string | undefined;
}

export interface UpdateVectorRequest {
    id?: string;
    class?: string | undefined;
    description?: string | undefined;
    collectionId?: string;
    embedding?: number[] | undefined;
}

export interface VectorSimilarityRequest {
    collectionId?: string;
    embeddings?: number[] | undefined;
}

export interface VectorSimilarityResponse {
    classes?: string[] | undefined;
}